language: php

env:
  global:
    - setup=stable

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 5.6
      env: setup=lowest
    - php: 7.0
    - php: 7.0
      env: setup=lowest
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: 7.3
    - php: 7.3
      env:
        - setup=lowest
    - php: 7.4
    - php: 7.4
      env:
          - setup=lowest

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest --prefer-lowest; fi

script:
  - vendor/bin/phpunit
